// Generated by CoffeeScript 1.6.2
var AttractionDemo, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AttractionDemo = (function(_super) {
  __extends(AttractionDemo, _super);

  function AttractionDemo() {
    _ref = AttractionDemo.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  AttractionDemo.prototype.setup = function(full) {
    var attraction, bounds, collide, i, max, min, p, wander, _i, _results;

    if (full == null) {
      full = true;
    }
    AttractionDemo.__super__.setup.call(this, full);
    min = new Vector(0.0, 0.0);
    max = new Vector(this.width, this.height);
    bounds = new EdgeBounce(min, max);
    this.physics.integrator = new Verlet();
    attraction = new Attraction(new Vector(this.width/2, this.height/2), 900, 900);
    collide = new Collision();
    max = full ? 10 : 10;
    _results = [];
    for (i = _i = 0; 0 <= max ? _i <= max : _i >= max; i = 0 <= max ? ++_i : --_i) {
	  var size_min = Math.min($(window).width() * 0.020,$(window).height() * 0.020);
	  var size_max = Math.min($(window).width() * 0.035,$(window).height() * 0.035);
	  p = new Particle(Random(size_min, size_max));
      p.setRadius(p.mass * 4);
      p.moveTo(new Vector(Random(this.width), Random(this.height)));
      p.behaviours.push(attraction);
      p.behaviours.push(bounds);
      p.behaviours.push(collide);
      collide.pool.push(p);
      _results.push(this.physics.particles.push(p));
    }
    return _results;
  };

  return AttractionDemo;

})(Demo);
